# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User01',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_01',
            },
        ),
        migrations.CreateModel(
            name='User02',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_02',
            },
        ),
    ]
