# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User02',
            new_name='User1',
        ),
        migrations.RenameModel(
            old_name='User01',
            new_name='User2',
        ),
        migrations.AlterModelTable(
            name='user1',
            table='user_1',
        ),
        migrations.AlterModelTable(
            name='user2',
            table='user_2',
        ),
    ]
